name: wap-prod

services:
  frontend:
    image: wap/frontend-${COMPOSE_PROJECT_NAME}:v0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    volumes:
      - ./frontend:/opt/frontend
      - ./tmp/fish_frontend/:/root/.local/share/fish/
    tty: true
    command: bash -c 'npm run build && npm run preview -- --host 0.0.0.0'
    ports:
      - "127.0.0.1:5173:5173"
      - "127.0.0.1:4173:4173"

#  nginx:
#    image: wap/nginx-${COMPOSE_PROJECT_NAME}:v0.0
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: nginx
#    ports:
#      - "5173:80"

  backend:
    image: wap/backend-${COMPOSE_PROJECT_NAME}:v0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    command: bash -c 'make run-prod'
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./backend:/opt/backend:Z
      - ./tmp/fish_backend/:/root/.local/share/fish/
    depends_on:
      - pgsql

  pgsql:
    image: wap/postgresql-${COMPOSE_PROJECT_NAME}:v0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wap_db
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./tmp/db/postgresql/pgsql:/var/lib/postgresql/data:Z
